# Use an official Python runtime as a parent image
FROM nginx:latest

# Copy the current directory contents into the container at /app
COPY . /usr/share/nginx/html

# Make port 80 available to the world outside this container
EXPOSE 80

 

 